apply plugin: 'com.android.application'

android {
    namespace = 'de.fau.cs.mad.carwatch'

    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    def getGitHash = { ->
        providers.exec {
            commandLine 'git', 'rev-parse', '--short', 'HEAD'
        }.standardOutput.asText.get().trim()
    }

    def getGitDate = { ->
        providers.exec {
            commandLine 'git', 'log', '-1', '--date=format:%Y%m%d_%H%M', '--pretty=format:%cd'
        }.standardOutput.asText.get().trim()
    }

    defaultConfig {
        applicationId = "de.fau.cs.mad.carwatch"
        minSdk = 23
        targetSdk = 36

        def versionMajor = 2
        def versionMinor = 5
        def versionPatch = 0
        versionName "${versionMajor}.${versionMinor}.${versionPatch}" + "_" + getGitDate() + "-" + getGitHash()
        versionCode versionMajor * 10000 + versionMinor * 100 + versionPatch
    }

    buildFeatures {
        dataBinding = true
        buildConfig = true
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.navigation:navigation-fragment:2.9.8'
    implementation 'androidx.navigation:navigation-ui:2.9.8'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'joda-time:joda-time:2.14.2'
    implementation 'com.orhanobut:logger:2.2.0'
    implementation 'org.zeroturnaround:zt-zip:1.17'

    implementation 'com.google.android.gms:play-services-mlkit-barcode-scanning:18.3.1'

    def room_version = "2.8.4"
    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version" // or kapt for Kotlin

    // Lifecycle (ViewModel, LiveData, etc.)
    def lifecycle_version = "2.10.0"
    implementation "androidx.lifecycle:lifecycle-viewmodel:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-livedata:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-runtime:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"
    annotationProcessor "androidx.lifecycle:lifecycle-common:$lifecycle_version" // or kapt for Kotlin

}


apply plugin: 'com.google.gms.google-services'
